[build]
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "cors", "serverless-http"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server2/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/main.html"
  status = 200
