[build]
  functions = "functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"
  # Include all Node modules you are using in your functions
  external_node_modules = ["express", "cors", "serverless-http"]
